/*
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package eu.eisti.calculation.client.api;

import eu.eisti.calculation.client.model.PricingCriteria;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PricingApi
 */
@Ignore
public class PricingApiTest {

    private final PricingApi api = new PricingApi();

    
    /**
     * Updates a Pricing form data
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updatePricingIdWithFormTest() {
        PricingCriteria body = null;
        Object response = api.updatePricingIdWithForm(body);

        // TODO: test validations
    }
    
}
